package com.resumeanalyzer.dto;

/**
 * DTO for responding with job description details.
 * Includes the ID generated by the backend.
 */
public class JobDescriptionResponse {
    private String id;
    private String title;
    private String description;
    private String requiredSkills;
    private String preferredSkills;
    private String experienceLevel;

    // Constructors
    public JobDescriptionResponse() {
    }

    public JobDescriptionResponse(String id, String title, String description, String requiredSkills, String preferredSkills, String experienceLevel) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.requiredSkills = requiredSkills;
        this.preferredSkills = preferredSkills;
        this.experienceLevel = experienceLevel;
    }

    // Getters and Setters
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getRequiredSkills() {
        return requiredSkills;
    }

    public void setRequiredSkills(String requiredSkills) {
        this.requiredSkills = requiredSkills;
    }

    public String getPreferredSkills() {
        return preferredSkills;
    }

    public void setPreferredSkills(String preferredSkills) {
        this.preferredSkills = preferredSkills;
    }

    public String getExperienceLevel() {
        return experienceLevel;
    }

    public void setExperienceLevel(String experienceLevel) {
        this.experienceLevel = experienceLevel;
    }
}